name: Testes unitários action

on: [push]

jobs:
  testes-unitarios:
    runs-on: ubuntu-latest
    steps:
      #copia o código para o runner
      - uses: actions/checkout@v3
      # configura o jdk dentro do runner
      - name: configurando JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: fazendo o build com maven
        run: mvn package